---
title: "3_EES_DV"
author: "Arturo Bertero"
date: "2024-03-31"
output: html_document
---

```{r}
library("pacman")
p_load(tidyverse, here, haven, countrycode, qgraph, bootnet, EGAnet, psych,
       huge, corclass)
```


# Input

```{r}
EES_CCA = read_rds(here("Input", "models", "EES_CCA.rds"))
EES_COR = read_rds(here("Input", "models", "EES_COR.rds"))
EES_EGA = read_rds(here("Input", "models", "EES_EGA.rds"))
EES_GGM_glasso = read_rds(here("Input", "models", "EES_GGM_glasso.rds"))
EES_GGM_huge = read_rds(here("Input", "models", "EES_GGM_huge.rds"))
```


# Processing

## EES_COR

```{r}
# EES_COR_constraint 
EES_COR_constraint = list()

# Loop for year 
for(year in names(EES_COR)) {
  EES_COR_constraint[[year]] = list()
  
  # Loop for country 
  for(country in names(EES_COR[[year]])) {
    # Get the absolute matrix 
    abs_matrix = abs(EES_COR[[year]][[country]])
    
    # Get the upper triangle 
    upper_tri = abs_matrix[upper.tri(abs_matrix)]
    
    # Calculate the mean value 
    mean_val = mean(upper_tri)
    
    # Store the mean value 
    EES_COR_constraint[[year]][[country]] = mean_val
  }
}

```

```{r}
# ASPL

# empty list 
EES_COR_aspl = list()

# Loop for years 
for (year in names(EES_COR)) {
  year_list = list()
  
  # Loop for countries in the inner layer of the original list
  for (country in names(EES_COR[[year]])) {
    
    # gather aspl data
    cent = centrality(EES_COR[[year]][[country]])
    spl = cent$ShortestPathLengths
    abs_spl = abs(spl)
    upper_tri_spl = abs_spl[upper.tri(abs_spl)]
    mean_val_spl = mean(upper_tri_spl)
    
    # Store results
    year_list[[country]] = mean_val_spl
  }
  EES_COR_aspl[[year]] = year_list
}

```

```{r}
#ratio pos/neg in integer numbers

# empty list 
EES_COR_np_i = list()

# Loop for year
for (year in names(EES_COR)) {
    EES_COR_np_i[[year]] = list()
    
    # Loop for country
    for (country_code in names(EES_COR[[year]])) {
        df = EES_COR[[year]][[country_code]]
        
        # upper triangle 
        upper_triangle = upper.tri(df)
        
        # count of positive values
        sum_positive = sum(df[upper_triangle] > 0)
        
        # count of negative values
        sum_negative = sum(df[upper_triangle] < 0)
        
        # ratio 
        ratio_neg_pos = sum_negative / sum_positive
        
        # Store the ratio 
        EES_COR_np_i[[year]][[country_code]] = ratio_neg_pos
    }
}

```

```{r}
#ratio pos/neg considering edge weights

# empty list 
EES_COR_np_w = list()

# Loop for year
for (year in names(EES_COR)) {
    EES_COR_np_w[[year]] = list()
    
    # Loop for country
    for (country_code in names(EES_COR[[year]])) {
        df = EES_COR[[year]][[country_code]]
        
        # upper triangle 
        upper_triangle = upper.tri(df)
        
        # sum of values of positive cells
        sum_positive = sum(df[upper_triangle][df[upper_triangle] > 0])
        
        # sum of negative cells
        sum_negative = sum(df[upper_triangle][df[upper_triangle] < 0])
        
        # ratio 
        ratio_neg_pos = sum_negative / sum_positive
        
        # Store the ratio
        EES_COR_np_w[[year]][[country_code]] = ratio_neg_pos
    }
}

```

## EES_GGM_glasso

```{r}
# EES_GGM_glasso_constraint 
EES_GGM_glasso_constraint = list()

# Loop for year 
for(year in names(EES_GGM_glasso)) {
  EES_GGM_glasso_constraint[[year]] = list()
  
  # Loop for country 
  for(country in names(EES_GGM_glasso[[year]])) {
    # Get the absolute matrix 
    abs_matrix = abs(EES_GGM_glasso[[year]][[country]])
    
    # Get the upper triangle 
    upper_tri = abs_matrix[upper.tri(abs_matrix)]
    
    # Calculate the mean value 
    mean_val = mean(upper_tri)
    
    # Store the mean value 
    EES_GGM_glasso_constraint[[year]][[country]] = mean_val
  }
}

```

```{r}
# ASPL

# empty list 
EES_GGM_glasso_aspl = list()

# Loop for years 
for (year in names(EES_GGM_glasso)) {
  year_list = list()
  
  # Loop for countries in the inner layer of the original list
  for (country in names(EES_GGM_glasso[[year]])) {
    
    # gather aspl data
    cent = centrality(EES_GGM_glasso[[year]][[country]])
    spl = cent$ShortestPathLengths
    abs_spl = abs(spl)
    upper_tri_spl = abs_spl[upper.tri(abs_spl)]
    mean_val_spl = mean(upper_tri_spl)
    
    # Store results
    year_list[[country]] = mean_val_spl
  }
  EES_GGM_glasso_aspl[[year]] = year_list
}

```

```{r}
#ratio pos/neg in integer numbers

# empty list 
EES_GGM_glasso_np_i = list()

# Loop for year
for (year in names(EES_GGM_glasso)) {
    EES_GGM_glasso_np_i[[year]] = list()
    
    # Loop for country
    for (country_code in names(EES_GGM_glasso[[year]])) {
        df = EES_GGM_glasso[[year]][[country_code]]
        
        # upper triangle 
        upper_triangle = upper.tri(df)
        
        # count of positive values
        sum_positive = sum(df[upper_triangle] > 0)
        
        # count of negative values
        sum_negative = sum(df[upper_triangle] < 0)
        
        # ratio 
        ratio_neg_pos = sum_negative / sum_positive
        
        # Store the ratio 
        EES_GGM_glasso_np_i[[year]][[country_code]] = ratio_neg_pos
    }
}

```

```{r}
#ratio pos/neg considering edge weights

# empty list 
EES_GGM_glasso_np_w = list()

# Loop for year
for (year in names(EES_GGM_glasso)) {
    EES_GGM_glasso_np_w[[year]] = list()
    
    # Loop for country
    for (country_code in names(EES_GGM_glasso[[year]])) {
        df = EES_GGM_glasso[[year]][[country_code]]
        
        # upper triangle 
        upper_triangle = upper.tri(df)
        
        # sum of values of positive cells
        sum_positive = sum(df[upper_triangle][df[upper_triangle] > 0])
        
        # sum of negative cells
        sum_negative = sum(df[upper_triangle][df[upper_triangle] < 0])
        
        # ratio 
        ratio_neg_pos = sum_negative / sum_positive
        
        # Store the ratio
        EES_GGM_glasso_np_w[[year]][[country_code]] = ratio_neg_pos
    }
}

```

## EES_GGM_huge

```{r}
# EES_GGM_huge_constraint 
EES_GGM_huge_constraint = list()

# Loop for year 
for(year in names(EES_GGM_huge)) {
  EES_GGM_huge_constraint[[year]] = list()
  
  # Loop for country 
  for(country in names(EES_GGM_huge[[year]])) {
    # Get the absolute matrix 
    abs_matrix = abs(EES_GGM_huge[[year]][[country]])
    
    # Get the upper triangle 
    upper_tri = abs_matrix[upper.tri(abs_matrix)]
    
    # Calculate the mean value 
    mean_val = mean(upper_tri)
    
    # Store the mean value 
    EES_GGM_huge_constraint[[year]][[country]] = mean_val
  }
}

```

```{r}
# ASPL

# empty list 
EES_GGM_huge_aspl = list()

# Loop for years 
for (year in names(EES_GGM_huge)) {
  year_list = list()
  
  # Loop for countries in the inner layer of the original list
  for (country in names(EES_GGM_huge[[year]])) {
    
    # gather aspl data
    cent = centrality(EES_GGM_huge[[year]][[country]])
    spl = cent$ShortestPathLengths
    abs_spl = abs(spl)
    upper_tri_spl = abs_spl[upper.tri(abs_spl)]
    mean_val_spl = mean(upper_tri_spl)
    
    # Store results
    year_list[[country]] = mean_val_spl
  }
  EES_GGM_huge_aspl[[year]] = year_list
}

```

```{r}
#ratio pos/neg in integer numbers

# empty list 
EES_GGM_huge_np_i = list()

# Loop for year
for (year in names(EES_GGM_huge)) {
    EES_GGM_huge_np_i[[year]] = list()
    
    # Loop for country
    for (country_code in names(EES_GGM_huge[[year]])) {
        df = EES_GGM_huge[[year]][[country_code]]
        
        # upper triangle 
        upper_triangle = upper.tri(df)
        
        # count of positive values
        sum_positive = sum(df[upper_triangle] > 0)
        
        # count of negative values
        sum_negative = sum(df[upper_triangle] < 0)
        
        # ratio 
        ratio_neg_pos = sum_negative / sum_positive
        
        # Store the ratio 
        EES_GGM_huge_np_i[[year]][[country_code]] = ratio_neg_pos
    }
}

```

```{r}
#ratio pos/neg considering edge weights

# empty list 
EES_GGM_huge_np_w = list()

# Loop for year
for (year in names(EES_GGM_huge)) {
    EES_GGM_huge_np_w[[year]] = list()
    
    # Loop for country
    for (country_code in names(EES_GGM_huge[[year]])) {
        df = EES_GGM_huge[[year]][[country_code]]
        
        # upper triangle 
        upper_triangle = upper.tri(df)
        
        # sum of values of positive cells
        sum_positive = sum(df[upper_triangle][df[upper_triangle] > 0])
        
        # sum of negative cells
        sum_negative = sum(df[upper_triangle][df[upper_triangle] < 0])
        
        # ratio 
        ratio_neg_pos = sum_negative / sum_positive
        
        # Store the ratio
        EES_GGM_huge_np_w[[year]][[country_code]] = ratio_neg_pos
    }
}

```

## Merge 

```{r}
# Function to convert list to df
convert_to_dataframe = function(list_name, name) {
  data_list = list()
  
  # Loop for year
  for (year in names(list_name)) {
    # Loop for country code
    for (country_code in names(list_name[[year]])) {
      value = list_name[[year]][[country_code]]
      
      # Create a data frame with original column names 
      data_df = data.frame(country = country_code, year = as.integer(year), value = value)
      
      # Rename the value column according to the name of the original list
      colnames(data_df)[3] = name
      
      # Append the data 
      data_list[[length(data_list) + 1]] = data_df
    }
  }
  
  # single data frame
  return(bind_rows(data_list))
}

# List of all lists 
list_names = list(EES_COR_aspl = "EES_COR_aspl", 
                   EES_COR_constraint = "EES_COR_constraint", 
                   EES_COR_np_i = "EES_COR_np_i", 
                   EES_COR_np_w = "EES_COR_np_w",
                   EES_GGM_glasso_aspl = "EES_GGM_glasso_aspl", 
                   EES_GGM_glasso_constraint = "EES_GGM_glasso_constraint", 
                   EES_GGM_glasso_np_i = "EES_GGM_glasso_np_i", 
                   EES_GGM_glasso_np_w = "EES_GGM_glasso_np_w",
                   EES_GGM_huge_aspl = "EES_GGM_huge_aspl", 
                   EES_GGM_huge_constraint = "EES_GGM_huge_constraint", 
                   EES_GGM_huge_np_i = "EES_GGM_huge_np_i", 
                   EES_GGM_huge_np_w = "EES_GGM_huge_np_w",
                   EES_CCA = "EES_CCA", 
                   EES_EGA = "EES_EGA")

# Empty list 
DV_list = list()

# Convert each list to a df
for (name in names(list_names)) {
  DV_list[[name]] = convert_to_dataframe(get(name), name)
}

# Merge all df into "DV"
DV = Reduce(function(x, y) merge(x, y, by = c("country", "year"), all = TRUE), DV_list)

```

```{r}
#manually change XXX in belgium
DV = DV %>% 
  mutate(country = ifelse(country == "XXX", "BEL", country)) %>% 
  arrange(country, year)
```


# Output

```{r}
saveRDS(DV, here("Input", "final_data", "DV.rds"))
```


