---
title: "Robustness checks"
author: "Arturo Bertero"
date: "2024-04-15"
output:
  html_document:
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, error = FALSE, message = FALSE, warning = FALSE)
```

```{r}
library("pacman")
p_load(tidyverse, here, haven, countrycode, vdemdata, psych, lavaan, ltm, patchwork,
       kableExtra, lme4, lmerTest)

#conflicts
conflict_prefer("select", "dplyr")
conflict_prefer("filter", "dplyr")
```

# Input

```{r}
# import final data
data = read_rds(here("Input", "final_data", "final.rds"))

#names
names(data)
```

# Processing

```{r}
# vote_choice as dummy
data <- data %>%
  mutate(vote_choice = ifelse(vote_choice == 0, 0, 1),  # Recode all nonzero values as 1
         vote_choice = factor(vote_choice, levels = c(0, 1), labels = c("No Vote", "Vote")))

```

```{r}
# party id
data <- data %>%
  mutate(part_id = ifelse(part_id < 0, NA, part_id))  # Replace negative values with NA

```

```{r}
# variable type
data <- data %>%
  mutate(
    vote = factor(vote, levels = c(0, 1), labels = c("No Vote", "Vote")), 
    sex = factor(sex, levels = c(1, 2), labels = c("Male", "Female")),  
    partisan = factor(partisan, levels = c(0, 1), labels = c("Non-Partisan", "Partisan")),  
    mand = factor(mand, levels = c(0, 1), labels = c("No", "Yes")),  
    
    year = as.integer(year),  
    yb = as.integer(yb),  
    class = as.integer(class),  
    Mean_Constraint = as.numeric(Mean_Constraint),  
    lr = as.numeric(lr),  
    pol_int = as.numeric(pol_int),  
    part_id = as.numeric(part_id),  
    age_d = as.numeric(age_d),  
    alt_inf = as.numeric(alt_inf),  
    educ = as.numeric(educ),  
    ideol = as.numeric(ideol),  
    mass_mob = as.numeric(mass_mob),  
    p_inst = as.numeric(p_inst),  
    pint = as.numeric(pint),  
    pola = as.numeric(pola),  
    turnout = as.numeric(turnout),  
    ihdi = as.numeric(ihdi),  
    ENEP = as.numeric(ENEP),  
    gallagher = as.numeric(gallagher),  
    gdp = as.numeric(gdp),  
    inflation = as.numeric(inflation),  
    turnout_nat = as.numeric(turnout_nat),  
    PAP_partisans = as.numeric(PAP_partisans),  
    LAP_partisans = as.numeric(LAP_partisans),  
    PAP_electorate = as.numeric(PAP_electorate),  
    LAP_electorate = as.numeric(LAP_electorate)  
  )

```

```{r}
# due checks
# Check variable types
str(data)

# Check factor distributions
table(data$vote, useNA = "always")
table(data$vote_choice, useNA = "always")
table(data$sex, useNA = "always")
table(data$partisan, useNA = "always")

# Check for missing values
summary(data)

```

## Model

### Baseline

```{r}
# Fit a logistic multilevel model 
m1 <- glmer(vote ~ Mean_Constraint + (1 | country_year), 
            data = data, 
            family = binomial())

summary(m1)

```

```{r}
# Fit a logistic multilevel model 
m2 <- glmer(vote_choice ~ Mean_Constraint + (1 | country_year), 
            data = data, 
            family = binomial())

summary(m2)
```

### Controls

```{r}
# Fit a logistic multilevel model with controls
m2 <- glmer(vote ~ Mean_Constraint + sex + yb + class + educ + 
                      lr + pol_int + partisan + 
                      pola + p_inst + ENEP + gallagher + 
                      gdp + turnout_nat + mand + 
                      (1 | country_year), 
            data = data, 
            family = binomial())

summary(m2)

```



























