
```{r}
library("pacman")
p_load(tidyverse, here, haven, countrycode, vdemdata, psych, lavaan, ltm,
       janitor, conflicted, sjPlot, BMA, BMS, fastDummies)

#conflicts
conflict_prefer("select", "dplyr")
conflict_prefer("filter", "dplyr")
```

# Input

```{r}
# import final data
data = read_rds(here("Input", "final_data", "final.rds"))

#as factor
data$country = as.factor(data$country)
data$year = as.factor(data$year)
data$country_year = as.factor(data$country_year)
```


```{r}
# data preparation for BMA package

# create matrix of IV
IV = data %>% 
  select(country, year, alt_inf:pola, ihdi:gallagher)

# create vectors for response variables (constraint and aspl)
DV_cor_cons = data %>% 
  pull(EES_COR_constraint) 

DV_cor_aspl = data %>% 
  pull(EES_COR_aspl)

DV_glasso_cons = data %>% 
  pull(EES_GGM_glasso_constraint)

DV_glasso_aspl = data %>% 
  pull(EES_GGM_glasso_aspl)

DV_huge_cons = data %>% 
  pull(EES_GGM_huge_constraint)

DV_huge_aspl = data %>% 
  pull(EES_GGM_huge_aspl)
```

```{r}
# data preparation for bms 

bms <- data %>%
  # Creating dummy variables for 'country' and 'year'
  dummy_cols(select_columns = c("country", "year"), remove_selected_columns = T) %>% 
  # exclude one dummy for country and one for year
  select(-c(country_AUT, year_1989))

# create data frame with DV as first col
#cor_cons
bms_cor_cons = bms %>% 
  select(EES_COR_constraint, alt_inf:gallagher, country_BEL:year_2019)

#cor_aspl
bms_cor_aspl = bms %>% 
  select(EES_COR_aspl, alt_inf:gallagher, country_BEL:year_2019)

# glasso_cor
bms_glasso_cons = bms %>% 
  select(EES_GGM_glasso_constraint, alt_inf:gallagher, country_BEL:year_2019)

# glasso_aspl
bms_glasso_aspl = bms %>% 
  select(EES_GGM_glasso_aspl, alt_inf:gallagher, country_BEL:year_2019)

# huge_cor
bms_huge_cons = bms %>% 
  select(EES_GGM_huge_constraint, alt_inf:gallagher, country_BEL:year_2019)

# huge_aspl
bms_huge_aspl = bms %>% 
  select(EES_GGM_huge_aspl, alt_inf:gallagher, country_BEL:year_2019)
```

# Processing

## BMA with BMA package

### BMA for cor

```{r}
# constraint
cor_cons = bicreg(IV, DV_cor_cons)
summary(cor_cons) # this model involves pint and pola 
```

```{r}
# aspl
cor_aspl = bicreg(IV, DV_cor_aspl)
summary(cor_aspl) # educ, mass_mob, pint, pola
```

### BMA for glasso

```{r}
# cor
glasso_cor = bicreg(IV, DV_glasso_cons)
summary(glasso_cor) # p_inst and ENEP
```

```{r}
# aspl
glasso_aspl = bicreg(IV, DV_glasso_aspl)
summary(glasso_aspl) # educ and pint
```

### BMA for huge

```{r}
# cor 
huge_cor = bicreg(IV, DV_huge_cons)
summary(huge_cor) # pint and pola
```

```{r}
# aspl 
huge_aspl = bicreg(IV, DV_huge_aspl)
summary(huge_aspl) # pint and ihdi
```

## BMA with BMS package

### BMA for cor

```{r}
# constraint

model_cor_con <- bms(bms_cor_cons, fixed.reg = c(
"country_BEL","country_BGR", "country_CYP",  "country_CZE","country_DEU",
"country_DNK","country_ESP", "country_EST",  "country_FIN","country_FRA","country_GBR",
"country_GRC", "country_HRV", "country_HUN","country_IRL","country_ITA",
"country_LTU", "country_LUX", "country_LVA","country_MLT","country_NLD",
"country_POL", "country_PRT", "country_ROU","country_SVK","country_SVN",
"country_SWE", "year_1994"  ,"year_1999"  ,"year_2004",
"year_2009", "year_2014","year_2019"))

estimates.bma(model_cor_con) # pip > 50 for pola
```

```{r}
# aspl

model_cor_aspl <- bms(bms_cor_aspl, fixed.reg = c(
"country_BEL","country_BGR", "country_CYP",  "country_CZE","country_DEU",
"country_DNK","country_ESP", "country_EST",  "country_FIN","country_FRA","country_GBR",
"country_GRC", "country_HRV", "country_HUN","country_IRL","country_ITA",
"country_LTU", "country_LUX", "country_LVA","country_MLT","country_NLD",
"country_POL", "country_PRT", "country_ROU","country_SVK","country_SVN",
"country_SWE", "year_1994"  ,"year_1999"  ,"year_2004",
"year_2009", "year_2014","year_2019"))

estimates.bma(model_cor_aspl) # no pip > 50 
```

### BMA for glasso

```{r}
# constraint

model_glasso_con <- bms(bms_glasso_cons, fixed.reg = c(
"country_BEL","country_BGR", "country_CYP",  "country_CZE","country_DEU",
"country_DNK","country_ESP", "country_EST",  "country_FIN","country_FRA","country_GBR",
"country_GRC", "country_HRV", "country_HUN","country_IRL","country_ITA",
"country_LTU", "country_LUX", "country_LVA","country_MLT","country_NLD",
"country_POL", "country_PRT", "country_ROU","country_SVK","country_SVN",
"country_SWE", "year_1994"  ,"year_1999"  ,"year_2004",
"year_2009", "year_2014","year_2019"))

estimates.bma(model_glasso_con) # no pip > 50 
```

```{r}
# aspl

model_glasso_aspl <- bms(bms_glasso_aspl, fixed.reg = c(
"country_BEL","country_BGR", "country_CYP",  "country_CZE","country_DEU",
"country_DNK","country_ESP", "country_EST",  "country_FIN","country_FRA","country_GBR",
"country_GRC", "country_HRV", "country_HUN","country_IRL","country_ITA",
"country_LTU", "country_LUX", "country_LVA","country_MLT","country_NLD",
"country_POL", "country_PRT", "country_ROU","country_SVK","country_SVN",
"country_SWE", "year_1994"  ,"year_1999"  ,"year_2004",
"year_2009", "year_2014","year_2019"))

estimates.bma(model_glasso_aspl) #pip > 50 pola pint p_inst
```

### BMA for huge

```{r}
# constraint

model_huge_con <- bms(bms_huge_cons, fixed.reg = c(
"country_BEL","country_BGR", "country_CYP",  "country_CZE","country_DEU",
"country_DNK","country_ESP", "country_EST",  "country_FIN","country_FRA","country_GBR",
"country_GRC", "country_HRV", "country_HUN","country_IRL","country_ITA",
"country_LTU", "country_LUX", "country_LVA","country_MLT","country_NLD",
"country_POL", "country_PRT", "country_ROU","country_SVK","country_SVN",
"country_SWE", "year_1994"  ,"year_1999"  ,"year_2004",
"year_2009", "year_2014","year_2019"))

estimates.bma(model_huge_con) # no pip > 50 
```

```{r}
# aspl

model_huge_aspl <- bms(bms_huge_aspl, fixed.reg = c(
"country_BEL","country_BGR", "country_CYP",  "country_CZE","country_DEU",
"country_DNK","country_ESP", "country_EST",  "country_FIN","country_FRA","country_GBR",
"country_GRC", "country_HRV", "country_HUN","country_IRL","country_ITA",
"country_LTU", "country_LUX", "country_LVA","country_MLT","country_NLD",
"country_POL", "country_PRT", "country_ROU","country_SVK","country_SVN",
"country_SWE", "year_1994"  ,"year_1999"  ,"year_2004",
"year_2009", "year_2014","year_2019"))

estimates.bma(model_huge_aspl) #pip > 50 pola p_inst
```




